spring.application.name=SpringAI

server.port=8081

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
#spring.ai.ollama.chat.options.model=gemma3

#For tool calling use -- qwen3:8b
spring.ai.ollama.chat.options.model=qwen3:8b

spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=springAI


spring.datasource.url=jdbc:postgresql://localhost:5432/springAI
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always